### ISSUE TITLE
NeoJSON parser errors when logging in for some users

### ISSUE THREAD

**Issue by Balletie** [Balletie/GitHub#5]
For some users, when they log in they get NeoJSON parser errors. This might be due to filling in invalid credentials (leading to a failure response), or some other unknown cases where the credentials were valid but result in an error anyway.

As for the first case (invalid credentials), this is related with issue #4, as failure responses can't be handled and checked on yet.

**Comment by Balletie** [comment]
Fixed by #18?

**Comment by jecisc** [comment]
I got an `MessageNotUnderstood: NeoJSONObjectMapping>>allowNil` error :)

**Comment by jecisc** [comment]
If I load by hand NeoJSON and try to authenticate I got `MessageNotUnderstood: GHLoggedInUser>>clientCopy`

**Comment by Balletie** [comment]
Commit 4592b9a29aa12b552e0c8c959613e669fb192cfd changed it to #bleedingEdge, which should load the latest versions no?

The tool is still bugged at the moment

**Comment by Balletie** [comment]
Confirmed by @jecisc to work. Closing for now until someone else reports problems.
